info:
  contactEmail: philip.whiles@ons.gov.uk

liquibase:
  user: postgres
  password: postgres
  default-schema: action
  url: jdbc:postgresql://localhost:5432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: false
  user:
    name: admin
    password: secret

management:
  port: 8261
  context-path: /mgmt
  security:
    role: SUPERUSER
    enabled: false

server:
  port: 8161
  servlet-path: /mgmt

endpoints:
  autoconfig: 
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    sensitive: true
  mapping:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

spring:
  application:
    name: CTP ActionService

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: actionsvc
    password: actionsvc
    driverClassName: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          ddl-auto: update

