info:
  contactEmail: philip.whiles@ons.gov.uk
  version: ${project.version}
  commit: ${buildNumber}
  branch: ${scmBranch}
  buildTime: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    org.springframework: warn
    com.hazelcast: info
    uk.gov.ons.ctp: warn

liquibase:
  user: postgres
  password: postgres
  default-schema: action
  url: jdbc:postgresql://localhost:5432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: false
  user:
    name: admin
    password: secret

management:
  port: 8252
  context-path: /mgmt
  security:
    role: SUPERUSER
    enabled: false

server:
  port: 8152
  servlet-path: /mgmt

endpoints:
  autoconfig: 
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    sensitive: true
  mappings:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

spring:
  application:
    name: ONS ActionService

  activemq:
    broker-url: tcp://localhost:53445
    pooled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: actionsvc
    password: actionsvc
    driverClassName: org.postgresql.Driver
    test-on-borrow: true
    remove-abandoned: true
    validation-query: SELECT 1;
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update

action-distribution:
  instruction-max: 100
  retry-sleep-seconds: 30
  initial-delay-seconds: 60
  subsequent-delay-seconds: 120

plan-execution:
  retry-sleep-seconds: 30
  initial-delay-seconds: 30
  subsequent-delay-seconds: 3600

case-frame-svc:
  scheme: http
  host: localhost
  port: 8171
  case-by-case-get-path: /cases/{caseid}
  questionnaires-by-case-get-path: /questionnaires/case/{caseid}
  case-events-by-case-get-path: /cases/{caseid}/events
  case-events-by-case-post-path: /cases/{caseid}/events
  address-by-uprn-get-path: /addresses/{uprn}
  case-by-status-and-action-plan-path: /cases/actionplan/{actionplanid}

csv-ingest:
  directory: /tmp/csv
  file-pattern: '*.csv'
  #the poll-milliseconds property is not used at the moment due to a bug in spring context loading in integration tests
  poll-milliseconds: 10000


