info:
  contactEmail: philip.whiles@ons.gov.uk

    

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    org.springframework: INFO
    uk.gov.ons.ctp: DEBUG

liquibase:
  user: postgres
  password: postgres
  default-schema: action
  url: jdbc:postgresql://localhost:5432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: false
  user:
    name: admin
    password: secret

management:
  port: 8251
  context-path: /mgmt
  security:
    role: SUPERUSER
    enabled: false

server:
  port: 8151
  servlet-path: /mgmt

endpoints:
  autoconfig: 
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    sensitive: true
  mapping:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

spring:
  application:
    name: ONS ActionService

  activemq:
    in-memory: true
    pooled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: actionsvc
    password: actionsvc
    driverClassName: org.postgresql.Driver
    test-on-borrow: true
    remove-abandoned: true
    validation-query: SELECT 1;

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          ddl-auto: update

case-frame-svc:
  scheme: http
  host: localhost
  port: 8171
  case-by-case-get-path: /cases/{caseid}
  questionnaires-by-case-get-path: /questionnaires/case/{caseid}
  case-events-by-case-get-path: /cases/{caseid}/events
  case-events-by-case-post-path: /cases/{caseid}/events
  address-by-uprn-get-path: /addresses/{uprn}
