info:
  contactEmail: philip.whiles@ons.gov.uk
  version: ${project.version}
  commit: ${buildNumber}
  branch: ${scmBranch}
  buildTime: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    org.springframework: info
    com.hazelcast: info
    uk.gov.ons.ctp: debug

liquibase:
  user: postgres
  password: postgres
  default-schema: action
  url: jdbc:postgresql://localhost:5432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: false
  user:
    name: admin
    password: secret

management:
  port: 8251
  context-path: /mgmt
  security:
    roles: SUPERUSER
    enabled: false

server:
  port: 8151
  servlet-path: /mgmt

endpoints:
  autoconfig: 
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    sensitive: true
  mappings:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

spring:
  application:
    name: ONS ActionService
  sleuth:
    sampler:
      percentage: 10
      
  activemq:
    broker-url: tcp://localhost:53445
    pool:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: actionsvc
    password: actionsvc
    driverClassName: org.postgresql.Driver
    tomcat:
      max-active: 20
      remove-abandoned: true
      remove-abandoned-timeout: 180

  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update

  zipkin:
    enabled: false

action-distribution:
  instruction-max: 100
  retry-sleep-seconds: 30
  initial-delay-seconds: 60
  subsequent-delay-seconds: 60

plan-execution:
  retry-sleep-seconds: 30
  initial-delay-seconds: 90
  subsequent-delay-seconds: 60

case-svc:
  case-group-path: /casegroups/{caseGroupId}
  case-by-case-get-path: /cases/{caseid}
  case-events-by-case-get-path: /cases/{caseid}/events
  case-events-by-case-post-path: /cases/{caseid}/events
  address-by-uprn-get-path: /addresses/{uprn}
  case-by-status-and-action-plan-path: /cases/actionplan/{actionplanid}
  connection-config:
    scheme: http
    host: localhost
    port: 8171
    retry-attempts: 10
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000

csv-ingest:
  directory: /tmp/csv
  file-pattern: '*.csv'
  #the poll-milliseconds property is not used at the moment due to a bug in spring context loading in integration tests
  poll-milliseconds: 10000

deadxml:
  directory: /var/log/ctp/responsemanagement/actionsvc

