swagger: '2.0'
info:
  title: Action Service API
  description: Provide access to Action and ActionPlan information
  version: 8.12.0
schemes:
  - http
basePath: /action
produces:
  - application/json
tags:
  - name: Action
    description: Navigation of Action information
  - name: ActionPlan
    description: Management of ActionPlan information
paths:
  /actions/{actionid}:
    get:
      summary:  Get the action details for a specified action.
      description: |
        Return the action details for the supplied actionid.
      parameters:
        - name: Accept
          in: header
          description: Response type, application/json.
          required: false
          type: string
        - name: actionid
          description: Unique action Id.
          in: path
          required: true
          type: integer
      tags:
        - Response
      responses:
        '200':
          description: Details for a single action.
          schema:
              $ref: '#/definitions/Action'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /actions/case/{caseid}:
    get:
      summary:  Get all action details for a specified case.
      description: |
        Return all action details for the supplied caseid.
      parameters:
        - name: Accept
          in: header
          description: Response type, application/json.
          required: false
          type: string
        - name: caseid
          description: Unique case Id.
          in: path
          required: true
          type: integer
      tags:
        - Response
      responses:
        '200':
          description: All action details for a supplied caseid.
          schema:
            type: array
            items:
              $ref: '#/definitions/Action'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /actionplans:
    get:
      summary: Get all action plans.
      description: Return details of all action plans.
      parameters:
        - name: Accept
          in: header
          description: Response type, application/json.
          required: false
          type: string
      tags:
        - Response
      responses:
        '200':
          description: An array of action plans.
          schema:
            type: array
            items:
              $ref: '#/definitions/ActionPlan'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /actionplans/{actionplanid}:
    get:
      summary: Get information for the specified action plan.
      description: Return information for the supplied action plan code.
      parameters:
        - name: Accept
          in: header
          description: Response type, application/json.
          required: false
          type: string
        - name: actionplanid
          in: path
          description: Unique action plan Id.
          required: true
          type: integer
      tags:
        - Response
      responses:
        '200':
          description: A single action plan.
          schema:
              $ref: '#/definitions/ActionPlan'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Action:
    type: object
    properties:
      actionId:
        type: integer
        description: Unique action ID.
      caseId:
        type: integer
        description: Unique case identifier.
      actionPlanId:
        type: integer
        description: Unique action plan Id.
      actionStatus:
        type: string
        description: Action status.
      actionType:
        type: string
        description: Type of action.
      priority:
        type: string
        description: The priority of the Action
      situation:
        type: string
        description: Field status, e.g. allocated, unallocated.
      createdDateTime:
        type: string
        format: date-time
        description: Date and time the action was created.
      createdBy:
        type: string
        description: Creator of action.
  ActionPlan:
    type: object
    properties:
      actionPlanId:
        type: integer
        description: Unique Id of action plan.
      actionPlanName:
        type: string
        description: Name of action plan.
      description:
        type: string
        description: Description of action plan.
      rules:
        type: string
        description: Action plan steps.
  Error:
     type: object
     properties:
      code:
       type: string
      timestamp:
       type: string
      message:
       type: string
